// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR3coDbAYIE5vigdW66CjOpOjjigJvYRM',
    appId: '1:107132185119:web:7045d2c096a4e8690dc32a',
    messagingSenderId: '107132185119',
    projectId: 'shiv-36eee',
    authDomain: 'shiv-36eee.firebaseapp.com',
    storageBucket: 'shiv-36eee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWsTC9R1ugu0811Qtk_8VTQQFKuOmgMwk',
    appId: '1:107132185119:android:698f64a23b1edf230dc32a',
    messagingSenderId: '107132185119',
    projectId: 'shiv-36eee',
    storageBucket: 'shiv-36eee.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR3coDbAYIE5vigdW66CjOpOjjigJvYRM',
    appId: '1:107132185119:web:8aab01e5e2ca8a900dc32a',
    messagingSenderId: '107132185119',
    projectId: 'shiv-36eee',
    authDomain: 'shiv-36eee.firebaseapp.com',
    storageBucket: 'shiv-36eee.firebasestorage.app',
  );

}